In [1]:
import numpy as np

x = np.array([1,2,3,4,5])
print(x)

[1 2 3 4 5]


In [2]:
type(x)

numpy.ndarray

In [3]:
y = [1,2,3,4,5]
print(y)
type(y)

[1, 2, 3, 4, 5]


list

In [5]:
%timeit [j**4 for j in range(1,8)]

1.22 µs ± 79.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [6]:
import numpy as np

%timeit np.arange(1,9)**4

8.1 µs ± 596 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


# Array

In [8]:
import numpy as np

x = [1,2,3,4]
y = np.array(x)
print(y)
type(y)

[1 2 3 4]


numpy.ndarray

In [9]:
y

array([1, 2, 3, 4])

In [11]:
l = []
for i in range(1,5):
    int_1 = int(input("enter:"))
    l.append(int_1)
print(np.array(l))

enter:1
enter:2
enter:3
enter:4
[1 2 3 4]


# How to know that which type of dimension array

In [13]:
import numpy as np

x = [1,2,3,4,5]
y = np.array([1,2,3,4,5])
print(y)
print(type(y))
print(y.ndim)

[1 2 3 4 5]
<class 'numpy.ndarray'>
1


In [14]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)
print(arr2.ndim)

[[1 2 3 4]
 [5 6 7 8]]
2


In [15]:
arr2 = np.array([[1,2,3,4],[5,6,7]])   #when both arrays do not have same length
print(arr2)
print(arr2.ndim)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [17]:
arr3 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]]])   
print(arr3)
print(arr3.ndim)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]]
3


In [20]:
arn = np.array([1,2,3,4],ndmin = 10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10


# Zeros

In [21]:
import numpy as np

arr_zero = np.zeros(4)
print(arr_zero)
print(type(arr_zero))

[0. 0. 0. 0.]
<class 'numpy.ndarray'>


In [24]:
import numpy as np

#arr_zero = np.zeros(4)
ar_zero1 = np.zeros((3,4))
print(ar_zero1)
#print(arr_zero)
#print(type(arr_zero))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# 1's 

In [25]:
arr_one = np.ones(4)
print(arr_one)

[1. 1. 1. 1.]


In [27]:
arr_one2 = np.ones((2,4))
print(arr_one2)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Empty

In [28]:
ar_em = np.empty(4)
print(ar_em)

[1. 1. 1. 1.]


# Range Array

In [29]:
arr_rn = np.arange(4)
print(arr_rn)

[0 1 2 3]


In [33]:
arr_rn3 = np.arange((3))
print(arr_rn3)

[0 1 2]


# Diagonal element with 1's

In [32]:
arr_dia = np.eye(3)
print(arr_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [34]:
arr_dia = np.eye(3,5)
print(arr_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [35]:
arr_dia = np.eye(5,5)
print(arr_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Linspace

In [37]:
arr_lin = np.linspace(1,20,num=5)
print(arr_lin)

[ 1.    5.75 10.5  15.25 20.  ]


In [39]:
arr_lin = np.linspace(1,50,num=4)
print(arr_lin)

[ 1.         17.33333333 33.66666667 50.        ]


# NumPy Arrays with Random Numbers:-
# rand()

In [41]:
import numpy as np
var = np.random.rand(4)
print(var)

[0.0187831  0.09234213 0.58285494 0.97180951]


In [42]:
var = np.random.rand(4)
print(var)

[0.47449809 0.53932832 0.08429711 0.73669939]


In [43]:
var = np.random.rand(4)
print(var)

[0.69540149 0.13259496 0.33831446 0.6629839 ]


In [44]:
var1 = np.random.rand(2,5)
print(var1)

[[0.84939296 0.90897529 0.56367889 0.2726002  0.73245848]
 [0.92555977 0.56816613 0.94587271 0.91193879 0.82545326]]


In [45]:
var1 = np.random.rand(5,5)
print(var1)

[[0.7191411  0.35423594 0.9477598  0.08994087 0.99647142]
 [0.36509355 0.09255402 0.31066189 0.86706668 0.61102712]
 [0.30312211 0.06489034 0.84591267 0.51165858 0.52028158]
 [0.53206179 0.71658406 0.24371978 0.94209869 0.00189928]
 [0.96630802 0.45900511 0.88052039 0.11939874 0.96637478]]


In [46]:
var1 = np.random.rand(3,3)
print(var1)

[[0.79651873 0.38746603 0.14201732]
 [0.44331556 0.54441263 0.80861206]
 [0.77710844 0.73546279 0.44938387]]


# randn()

In [47]:
rar = np.random.randn(3)
print(rar)

[1.0127433  0.35949413 0.28888527]


In [49]:
rar = np.random.randn(3)
print(rar)

[-0.19129561 -0.48289013  1.06100728]


In [48]:
rar = np.random.randn(3,3)
print(rar)

[[-0.10861831 -1.91458672  0.09768598]
 [ 0.00877705  1.47964741  2.31498294]
 [-0.11665227  1.49105741 -2.52502042]]


# ranf()

In [50]:
ar_ranf = np.random.ranf(4)
print(ar_ranf)

[0.52005725 0.7721198  0.17477526 0.0549231 ]


In [51]:
ar_ranf = np.random.ranf(4)
print(ar_ranf)

[0.90597008 0.13438346 0.84496133 0.43999695]


In [52]:
ar_ranf = np.random.ranf(3,4)
print(ar_ranf)

TypeError: random_sample() takes at most 1 positional argument (2 given)

# randint()

In [53]:
# var4 = np.random.randint(min,max,total_values)

var4 = np.random.randint(5,20,5)
print(var4)

[10 14 19 17 19]


In [54]:
var4 = np.random.randint(5,20,7)
print(var4)

[ 8 17 10 18 16  6 16]


# Data Types:-

In [1]:
import numpy as np

var = np.array([1,2,3,4,5])
print("Data type:",var.dtype)

Data type: int32


In [2]:
var = np.array([1,2,3,4,5,45,67,89,34])
print("Data type:",var.dtype)

Data type: int32


In [3]:
var = np.array([1.56,2.87,3,4,5,89.65])
print("Data type:",var.dtype)

Data type: float64


In [4]:
var = np.array(['A','D','F'])
print("Data type:",var.dtype)

Data type: <U1


In [5]:
var = np.array([1,2,3,4,5,'A','Hello','Python',67.87])
print("Data type:",var.dtype)

Data type: <U32


In [6]:
x = np.array([1,2,3,4,5])
print("Data type:",x.dtype)

Data type: int32


In [7]:
x = np.array([1,2,3,4,5],dtype = np.int8)
print("Data type:",x.dtype)

Data type: int8


In [8]:
x = np.array([1,2,3,4,5], dtype = np.int32)
print("Data type:",x.dtype)

Data type: int32


In [9]:
x = np.array([1,2,3,4,5],dtype="f")
print("Data type:",x.dtype)

Data type: float32


In [10]:
x = np.array([1,2,3,4,5],dtype="S")
print("Data type:",x.dtype)

Data type: |S1


In [11]:
x = np.array([1,2,3,4,5],dtype="U")
print("Data type:",x.dtype)

Data type: <U1


In [12]:
x = np.array([1,2,3,4,5],dtype="c")
print("Data type:",x.dtype)

Data type: |S1


In [13]:
x = np.array([1,2,3,4,5],dtype="b")
print("Data type:",x.dtype)

Data type: int8


In [15]:
x1 = np.array([1,2,3,4])

new = np.float32(x1)
print("Data type:",x1.dtype)
print("Data type new:",new.dtype)
print(new)

Data type: int32
Data type new: float32
[1. 2. 3. 4.]


In [17]:
a = np.array([2,3,4,5])

new = np.complex128(a)

print("Data type:",new.dtype)
print(new)

Data type: complex128
[2.+0.j 3.+0.j 4.+0.j 5.+0.j]


# Arithmetic Operation:-

In [18]:
import numpy as np

# add------------------->

var = np.array([1,2,3,4,5])

varadd = var+3

print(varadd)

[4 5 6 7 8]


In [19]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([6,7,8,9,10])

varadd = var1+var2

print(varadd)

[ 7  9 11 13 15]


In [20]:
# Sub------------------------->

var1 = np.array([1,2,3,4,5])
var2 = np.array([6,7,8,9,10])

varsub = var1-var2

print(varsub)


[-5 -5 -5 -5 -5]


In [21]:
var1 = np.array([1,2,3,4,5])


varsub = var1-2

print(varsub)

[-1  0  1  2  3]


In [22]:
# Mul-------------------->

var1 = np.array([1,2,3,4,5])
var2 = np.array([6,7,8,9,10])

varMul = var1*var2

print(varMul)

[ 6 14 24 36 50]


In [23]:
var1 = np.array([1,2,3,4,5])


varMul = var1*4

print(varMul)

[ 4  8 12 16 20]


In [24]:
# Div------------------->

var1 = np.array([1,2,3,4,5])


vardiv = var1/3

print(vardiv)

[0.33333333 0.66666667 1.         1.33333333 1.66666667]


In [25]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([6,7,8,9,10])

vardiv = var1/var2

print(vardiv)

[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [27]:
# Mod---------------------->

var1 = np.array([1,2,3,4,5])
var2 = np.array([6,7,8,9,10])

varmod = var2%var1

print(varmod)

[0 1 2 1 0]


In [28]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([6,7,8,9,10])

varmod = var1%2

print(varmod)

[1 0 1 0 1]


In [29]:
# power----------------->

var1 = np.array([1,2,3,4,5])
#var2 = np.array([6,7,8,9,10])

varpower = var1**2

print(varpower)

[ 1  4  9 16 25]


In [30]:
var1 = np.array([1,2,3,4,5])
var2 = np.array([6,7,8,9,10])

varpower = var1**var2

print(varpower)

[      1     128    6561  262144 9765625]


In [31]:
# reciprocal----------------------->

var1 = np.array([1,2,3,4,5])
#var2 = np.array([6,7,8,9,10])

var = 1/var1

print(var)

[1.         0.5        0.33333333 0.25       0.2       ]


In [32]:
# add()------------------->

var1 = np.array([1,2,3,4,5])
#var2 = np.array([6,7,8,9,10])

varadd = np.add(var1,4)

print(varadd)

[5 6 7 8 9]


# 2D Array

In [38]:
arr21 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
arr22 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

varadd = arr21 + arr22

print(varadd)

[[ 2  4  6  8 10]
 [12 14 16 18 20]]


In [39]:
var1 = np.array([1,2,3,4,5])

var = np.reciprocal(var1)

print(var)

[1 0 0 0 0]


In [44]:
# max() and min()-------------->

var1 = np.array([1,2,3,4,5])
var2 = np.array([6,7,8,9,10])

varmax = np.max(var1)
varmin = np.min(var2)

print("Max",varmax)
print("Min",varmin)

Max 5
Min 6


In [45]:
var1 = np.array([13,46,67,32,10,-56])
var2 = np.array([66,73,8,9,10,34])

varmax = np.max(var1)
varmin = np.min(var2)

print("Max",varmax)
print("Min",varmin)

Max 67
Min 8


In [46]:
# argmin() and argmax()------------------>

var1 = np.array([1,2,3,4,5])

var = np.argmin(var1)
print("Argmin",var)

Argmin 0


In [47]:
var1 = np.array([1,2,3,4,5])

var = np.argmax(var1)
print("Argmax",var)

Argmax 4


In [48]:
var1 = np.array([45,23,65,32,78,212])

var = np.argmin(var1)
print("Argmin",var)

Argmin 1


In [49]:
var1 = np.array([45,23,65,212,78,32])

var = np.argmax(var1)
print("Argmax",var)

Argmax 3


In [51]:
# sqrt()---------------->

var1 = np.array([45,23,65,32,78,212])

var = np.sqrt(var1)
print("SQRT",var)
print(var.dtype)

SQRT [ 6.70820393  4.79583152  8.06225775  5.65685425  8.83176087 14.56021978]
float64


In [54]:
# sin()---------------->

var1 = np.array([4,5,3,8,2])

var = np.sin(var1)
print("Sin",var)
print(var.dtype)

Sin [-0.7568025  -0.95892427  0.14112001  0.98935825  0.90929743]
float64


In [56]:
# cos()--------------->

var1 = np.array([4,6,3,8,2])

var = np.cos(var1)
print("Cos",var)

Cos [-0.65364362  0.96017029 -0.9899925  -0.14550003 -0.41614684]


In [58]:
# np.cumsum(x)------------->
var1 = np.array([4,6,3,8,2])

var = np.cumsum(var1)
print("Cumsum",var)
print(var.dtype)

Cumsum [ 4 10 13 21 23]
int32


# Axis = 1

In [59]:
var1 = np.array([[4,6,3,8,2],[4,3,6,43,2]])

var = np.min(var1,axis = 1)
print("Min",var)

Min [2 2]


# Axis = 0

In [60]:
var1 = np.array([[4,6,3,8,2],[4,3,6,43,2]])

var = np.max(var1,axis = 0)
print("Max",var)

Max [ 4  6  6 43  2]


In [61]:
var1 = np.array([[4,6,3,8,2],[4,3,6,43,2]])

var = np.min(var1,axis = 0)
print("Min",var)

Min [4 3 3 8 2]


In [62]:
var1 = np.array([4,6,3,8,2])

var = np.min(var1,axis = 0)
print("Min",var)

Min 2


# Shape

In [63]:
arr = np.array([[1,2],[1,2]])

print(arr)
print()
print("Shape:",arr.shape)

[[1 2]
 [1 2]]

Shape: (2, 2)


In [64]:
arr = np.array([[1,2],[1,2],[3,5]])

print(arr)
print()
print("Shape:",arr.shape)

[[1 2]
 [1 2]
 [3 5]]

Shape: (3, 2)


In [65]:
arr = np.array([[1,2,3],[1,2,4],[3,5,6]])

print(arr)
print()
print("Shape:",arr.shape)

[[1 2 3]
 [1 2 4]
 [3 5 6]]

Shape: (3, 3)


In [69]:
arr = np.array([1,2,3,5],ndmin = 4)

print(arr)
print()
print("Shape:",arr.shape)
print()
print(arr.ndim)

[[[[1 2 3 5]]]]

Shape: (1, 1, 1, 4)

4


# Reshape

In [72]:
arr1 = np.array([1,2,3,4,5,6])

print(arr1)
print()
x = arr1.reshape(3,2)         # arr.reshape(number of rows,number of elements)
print(x)

[1 2 3 4 5 6]

[[1 2]
 [3 4]
 [5 6]]


In [73]:
arr2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(arr2)
print(arr2.ndim)
print()
nw = arr2.reshape(2,3,2)
print(nw)
print(nw.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3


# Broadcasting 

In [74]:
import numpy as np

arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3])
print(arr1+arr2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [75]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([1,2,3,4])
print(arr1+arr2)

[2 4 6 8]


In [80]:
arr1 = np.array([1,2,3])
print(arr1.shape)
print()
print(arr1)
print()

arr2 = np.array([[1],[2],[3]])
print(arr2.shape)
print()
print(arr2)
print()

print("add:",arr1+arr2)

(3,)

[1 2 3]

(3, 1)

[[1]
 [2]
 [3]]

add: [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [82]:
arr1 = np.array([1,2,3])
print(arr1.shape)
print()
print(arr1)
print()

arr2 = np.array([[1],[2],[3]])
print(arr2.shape)
print()
print(arr2)
print()

print("add:",arr1+arr2)

(3,)

[1 2 3]

(3, 1)

[[1]
 [2]
 [3]]

add: [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [84]:
x = np.array([[1],[2]])
print(x.shape)

y = np.array([[1,2,3],[1,2,3]])
print(y.shape)

print()
print(x+y)

(2, 1)
(2, 3)

[[2 3 4]
 [3 4 5]]


# Indexing

In [1]:
# 1D-------------->

import numpy as np

arr = np.array([8,6,5,9])
print(arr[1])

6


In [2]:
print(arr[-2])

5


In [5]:
# 2D---------------->

arr1 = np.array([[3,4,6],[7,5,8]])
print(arr1)
print(arr1.ndim)
print()
print(arr1[0,2])

[[3 4 6]
 [7 5 8]]
2

6


In [6]:
print(arr1[1,1])

5


In [7]:
# 3D---------------->

arr2 = np.array([[[3,5,6],[7,8,9],[4,2,1]]])
print(arr2)
print(arr2.ndim)
print()
print(arr2[0,2])

[[[3 5 6]
  [7 8 9]
  [4 2 1]]]
3

[4 2 1]


In [8]:
print(arr2[0,0,2])

6


In [9]:
print(arr2[0,1,1])

8


In [10]:
print(arr2[0,2,2])

1


In [11]:
print(arr2[0,0,0])

3


# Slicing NumPy Arrays


In [12]:
# 1D----------->

x = np.array([1,2,3,4,5,6,7])
print(x)
print()
print(x.type)

[1 2 3 4 5 6 7]

int32


In [13]:
print(type(x))

<class 'numpy.ndarray'>


In [14]:
print("2 to 5:",x[1:5])

2 to 5: [2 3 4 5]


In [15]:
print(x[0:3])

[1 2 3]


In [16]:
print(x[0:6:2])

[1 3 5]


In [17]:
print(x[1:])

[2 3 4 5 6 7]


In [18]:
print(x[:])

[1 2 3 4 5 6 7]


In [19]:
print(x[:4])

[1 2 3 4]


In [20]:
print(x[::])

[1 2 3 4 5 6 7]


In [21]:
print(x[:-1])

[1 2 3 4 5 6]


In [22]:
print(x[-1:-6])

[]


In [23]:
print(x[-1:1])

[]


In [24]:
print(x[0:-1])

[1 2 3 4 5 6]


In [26]:
# 2D--------->

y = np.array([[1,2,3],[4,5,6]])
print(y[0,1:])

[2 3]


In [27]:
y = np.array([[1,2,3],[4,5,6]])
print(y[0,0:1])

[1]


In [29]:
print(y[1,0:3])

[4 5 6]


In [32]:
# 3D------------->

z = np.array([[1,2,3],[4,5,6],[7,6,8]])
print(z)

print(z[0,1:])

[[1 2 3]
 [4 5 6]
 [7 6 8]]
[2 3]


In [33]:
print(z[2,1:])

[6 8]


In [34]:
print(z[1,0:])

[4 5 6]


# Iterating NumPy Arrays 

In [35]:
x = [2,3,4,5,6]
for i in x:
    print(i)

2
3
4
5
6


In [36]:
# 1D------------>

import numpy as np

arr = np.array([3,4,5,7,6])
for i in arr:
    print(i)

3
4
5
7
6


In [37]:
# 2D--------------->

arr1 = np.array([[2,3,4,5],[6,7,9,8]])
for i in arr1:
    print(i)

[2 3 4 5]
[6 7 9 8]


In [38]:
for k in arr1:
    for l in k:
        print(l)

2
3
4
5
6
7
9
8


In [40]:
# 3D--------------->

arr2 = np.array([[[1,2,3,4],[5,4,6,7],[9,7,6,8]]])
print(arr2)
print(arr1.ndim)
print()

for i in arr2:
    print(i)
    for j in i:
        for k in j:
            print(k)

[[[1 2 3 4]
  [5 4 6 7]
  [9 7 6 8]]]
2

[[1 2 3 4]
 [5 4 6 7]
 [9 7 6 8]]
1
2
3
4
5
4
6
7
9
7
6
8


In [41]:
# nditer()-------------->

arr2 = np.array([[[1,2,3,4],[5,4,6,7],[9,7,6,8]]])
print(arr2)
print(arr1.ndim)
print()

for i in np.nditer(arr2):
    print(i)
    

[[[1 2 3 4]
  [5 4 6 7]
  [9 7 6 8]]]
2

1
2
3
4
5
4
6
7
9
7
6
8


In [42]:
arr2 = np.array([[[1,2,3,4],[5,4,6,7],[9,7,6,8]]])
print(arr2)
print(arr1.ndim)
print()

for i in np.nditer(arr2,flags = ['buffered'],op_dtypes=["S"]):
    print(i)
    

[[[1 2 3 4]
  [5 4 6 7]
  [9 7 6 8]]]
2

b'1'
b'2'
b'3'
b'4'
b'5'
b'4'
b'6'
b'7'
b'9'
b'7'
b'6'
b'8'


In [44]:
# ndenumerate()----------->

arr2 = np.array([[[1,2,3,4],[5,4,6,7],[9,7,6,8]]])
print(arr2)
print(arr1.ndim)
print()

for i,d in np.ndenumerate(arr2):
    print(i,d)

[[[1 2 3 4]
  [5 4 6 7]
  [9 7 6 8]]]
2

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 1, 0) 5
(0, 1, 1) 4
(0, 1, 2) 6
(0, 1, 3) 7
(0, 2, 0) 9
(0, 2, 1) 7
(0, 2, 2) 6
(0, 2, 3) 8


# Copy vs View in NumPy Arrays

In [45]:
import numpy as np

var = np.array([1,2,3,4,5])

co = var.copy()
print("var",var)
print("copy",co)

var [1 2 3 4 5]
copy [1 2 3 4 5]


In [46]:
v = np.array([3,4,6,7])
vi = v.view()
print("Var",v)
print("View",vi)

Var [3 4 6 7]
View [3 4 6 7]


# Difference between copy and view

In [47]:
var = np.array([1,2,3,4,5])

co = var.copy()
var[1]=40
print("var",var)
print("copy",co)

var [ 1 40  3  4  5]
copy [1 2 3 4 5]


In [48]:
v = np.array([3,4,6,7])
vi = v.view()
v[1]=50
print("Var",v)
print("View",vi)

Var [ 3 50  6  7]
View [ 3 50  6  7]


In [49]:
var = np.array([1,2,3,4,5])

co = var.copy()
co[1]=60
print("var",var)
print("copy",co)

var [1 2 3 4 5]
copy [ 1 60  3  4  5]


In [50]:
v = np.array([3,4,6,7])
vi = v.view()
vi[1]=30
print("Var",v)
print("View",vi)

Var [ 3 30  6  7]
View [ 3 30  6  7]


# Join and Spilt Functions

In [51]:
import numpy as np

var = np.array([1,2,3,4])
var1 = np.array([4,5,7,8])

ar = np.concatenate((var,var1))

print(ar)

[1 2 3 4 4 5 7 8]


In [52]:
var = np.array([[1,2,3,4],[5,6,8,3]])
var1 = np.array([[4,5,7,8],[3,5,8,9]])

ar = np.concatenate((var,var1),axis=1)

print(ar)

[[1 2 3 4 4 5 7 8]
 [5 6 8 3 3 5 8 9]]


In [54]:
# stack()----------->

var = np.array([1,2,3,4])
var1 = np.array([4,5,7,8])

ar = np.stack((var,var1),axis = 1)

print(ar)

[[1 4]
 [2 5]
 [3 7]
 [4 8]]


In [55]:
var = np.array([1,2,3,4])
var1 = np.array([4,5,7,8])

ar = np.stack((var,var1),axis = 0)

print(ar)

[[1 2 3 4]
 [4 5 7 8]]


In [57]:
var = np.array([1,2,3,4])
var1 = np.array([4,5,7,8])

ar = np.dstack((var,var1))    # dstack hinght

print(ar)

[[[1 4]
  [2 5]
  [3 7]
  [4 8]]]


In [58]:
var = np.array([1,2,3,4])
var1 = np.array([4,5,7,8])

ar = np.vstack((var,var1))    # vstack column

print(ar)

[[1 2 3 4]
 [4 5 7 8]]


In [59]:
var = np.array([1,2,3,4])
var1 = np.array([4,5,7,8])

ar = np.hstack((var,var1))     # hstack row

print(ar)

[1 2 3 4 4 5 7 8]


# Split array

In [63]:
var = np.array([1,2,3,4,5,6,7,8])

print(var)

print()

new = np.array_split(var,4)
print(new)
print(type(new))

[1 2 3 4 5 6 7 8]

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]
<class 'list'>


In [64]:
print(new[0])

[1 2]


In [65]:
var = np.array([[1,2,3,4],[5,6,7,8]])

print(var)

print()

new = np.array_split(var,3)
print(new)
print(type(new))

[[1 2 3 4]
 [5 6 7 8]]

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([], shape=(0, 4), dtype=int32)]
<class 'list'>


In [66]:
var = np.array([[1,2,3,4],[5,6,7,8]])

print(var)

print()

new = np.array_split(var,4)
print(new)
print(type(new))

[[1 2 3 4]
 [5 6 7 8]]

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([], shape=(0, 4), dtype=int32), array([], shape=(0, 4), dtype=int32)]
<class 'list'>


In [67]:
var = np.array([[1,2,3,4],[5,6,7,8]])

print(var)

print()

new = np.array_split(var,4,axis = 1)
print(new)
print(type(new))

[[1 2 3 4]
 [5 6 7 8]]

[array([[1],
       [5]]), array([[2],
       [6]]), array([[3],
       [7]]), array([[4],
       [8]])]
<class 'list'>


# Searching

In [68]:
import numpy as np

var = np.array([2,4,5,7,8,9,2,4,5])

x = np.where(var == 2)
print(x)

(array([0, 6], dtype=int64),)


In [69]:
x = np.where(var == 5)
print(x)

(array([2, 8], dtype=int64),)


In [70]:
x = np.where(var == 8)
print(x)

(array([4], dtype=int64),)


In [72]:
x = np.where( (var%2) == 0)
print(x)

(array([0, 1, 4, 6, 7], dtype=int64),)


In [74]:
var1 = np.array([2,4,5,7,8,9,2,4,5])

x1= np.searchsorted(var1,5)
print(x1)

2


In [75]:
var1 = np.array([2,4,5,7,8,9,2,4,5])

x1= np.searchsorted(var1,8)
print(x1)

4


In [76]:
var1 = np.array([2,4,5,7,8,9,2,4,5])

x1= np.searchsorted(var1,9,side = 'right')
print(x1)

9


In [77]:
var1 = np.array([2,4,5,7,8,9,2,4,5])

x1= np.searchsorted(var1,[1,3,10],side = 'right')
print(x1)

[0 1 9]


# Sort

In [78]:
var1 = np.array([2,4,5,7,8,9,2,4,5])

x1= np.sort(var1)
print(x1)

[2 2 4 4 5 5 7 8 9]


In [81]:
var1 = np.array(['A','S','D','f','i','Hey'])

x1= np.sort(var1)
print(x1)

['A' 'D' 'Hey' 'S' 'f' 'i']


In [82]:
var1 = np.array([[2,4,5,7],[8,9,2,4]])

x1= np.sort(var1)
print(x1)

[[2 4 5 7]
 [2 4 8 9]]


# Filter Array

In [84]:
var_3 = np.array(["a","s","d","f"])

f = [True,False,False,True]

new_a = var_3[f]
print(new_a)
print(type(new_a))

['a' 'f']
<class 'numpy.ndarray'>


# Shuffle()

In [85]:
var = np.array([4,5,7,9,23])
np.random.shuffle(var)
print(var)

[ 9 23  7  5  4]


In [86]:
var = np.array([4,5,7,9,23])
np.random.shuffle(var)
print(var)

[ 4 23  5  9  7]


In [87]:
var = np.array([4,5,7,9,23])
np.random.shuffle(var)
print(var)


[ 5  9  4  7 23]


# Unique()

In [89]:
var = np.array([4,5,7,9,23,12,54,67])
x = np.unique(var,return_index = True)
print(x)

(array([ 4,  5,  7,  9, 12, 23, 54, 67]), array([0, 1, 2, 3, 5, 4, 6, 7], dtype=int64))


In [90]:
var = np.array([4,5,7,9,23,12,54,67])
x = np.unique(var,return_index = False)
print(x)

[ 4  5  7  9 12 23 54 67]


In [91]:
var = np.array([4,5,7,9,23,12,54,67])
x = np.unique(var,return_index = True,return_counts = True)
print(x)

(array([ 4,  5,  7,  9, 12, 23, 54, 67]), array([0, 1, 2, 3, 5, 4, 6, 7], dtype=int64), array([1, 1, 1, 1, 1, 1, 1, 1], dtype=int64))


# Resize()

In [92]:
var2 = np.array([1,2,3,4,5,6,7])

y = np.resize(var2,(2,3))
print(y)

[[1 2 3]
 [4 5 6]]


In [93]:
var2 = np.array([1,2,3,4,5,6,7])

y = np.resize(var2,(2,2))
print(y)

[[1 2]
 [3 4]]


In [94]:
var2 = np.array([1,2,3,4,5,6,7])

y = np.resize(var2,(3,2))
print(y)

[[1 2]
 [3 4]
 [5 6]]


# Flatten()

In [96]:
var2 = np.array([1,2,3,4,5,6,7])

y = np.resize(var2,(3,2))
print(y)
print()
print(y.flatten())

[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]


In [97]:
var2 = np.array([1,2,3,4,5,6,7])

y = np.resize(var2,(3,2))
print(y)
print()
print(y.flatten(order = "F"))

[[1 2]
 [3 4]
 [5 6]]

[1 3 5 2 4 6]


In [98]:
var2 = np.array([1,2,3,4,5,6,7])

y = np.resize(var2,(3,2))
print(y)
print()
print(y.flatten(order = "A"))

[[1 2]
 [3 4]
 [5 6]]

[1 2 3 4 5 6]


# Ravel()

In [99]:
var2 = np.array([1,2,3,4,5,6,7])

y = np.resize(var2,(3,2))
print(y)
print()
print(y.flatten(order = "F"))
print("Ravel", np.ravel(y,order="A"))

[[1 2]
 [3 4]
 [5 6]]

[1 3 5 2 4 6]
Ravel [1 2 3 4 5 6]


In [101]:
var2 = np.array([1,2,3,4,5,6,7])

y = np.resize(var2,(3,2))
print(y)
print()
print(y.flatten(order = "F"))
print("Ravel", np.ravel(y,order="C"))

[[1 2]
 [3 4]
 [5 6]]

[1 3 5 2 4 6]
Ravel [1 2 3 4 5 6]


# Insert()

In [104]:
x = np.array([2,3,5,7])

print(x)
print()

y = np.insert(x, 2,50)
print(y)

[2 3 5 7]

[ 2  3 50  5  7]


In [106]:
x = np.array([2,3,5,7])

print(x)
print()

y = np.insert(x, 2,(50,70))
print(y)

[2 3 5 7]

[ 2  3 50 70  5  7]


In [109]:
x = np.array([2,3,5,7])

print(x)
print()

y = np.insert(x, (2,3), 40)
print(y)

[2 3 5 7]

[ 2  3 40  5 40  7]


In [110]:
x = np.array([2,3,5,7])

print(x)
print()

y = np.insert(x, 2, 8.6 )
print(y)

[2 3 5 7]

[2 3 8 5 7]


In [113]:
x = np.array([[2,3,5],[7,6,9]])

print(x)
print()

y = np.insert(x, 2, [22,11] , axis = 1)
print(y)

[[2 3 5]
 [7 6 9]]

[[ 2  3 22  5]
 [ 7  6 11  9]]


In [114]:
x = np.array([2,3,5,7])

print(x)
print()

y = np.append(x, 8.6 )
print(y)

[2 3 5 7]

[2.  3.  5.  7.  8.6]


In [115]:
x = np.array([[2,3,5],[7,6,9]])

print(x)
print()

y = np.append(x, [[22,11,33]] , axis = 0)
print(y)

[[2 3 5]
 [7 6 9]]

[[ 2  3  5]
 [ 7  6  9]
 [22 11 33]]


# Delete()

In [116]:
x = np.array([2,3,5,7])

print(x)
print()

y = np.delete(x, 2 )
print(y)

[2 3 5 7]

[2 3 7]


# Matrix in NumPy Arrays

In [121]:
import numpy as np

var = np.matrix([[1,2,3],[4,5,6]])
print(var)

print(type(var))

[[1 2 3]
 [4 5 6]]
<class 'numpy.matrix'>


In [120]:
var1 = np.array([[1,2,3],[4,5,6]])
print(var1)
print(type(var1))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [122]:
var1 = np.matrix([[1,2,3],[4,5,6]])
var2 = np.matrix([[1,2,3],[4,5,6]])
print(var1)
print(var2)

print()
print(var1+var2)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]

[[ 2  4  6]
 [ 8 10 12]]


In [123]:
var1 = np.matrix([[1,2,3],[4,5,6]])
var2 = np.matrix([[1,2,3],[4,5,6]])
print(var1)
print(var2)

print()
print(var1-var2)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]

[[0 0 0]
 [0 0 0]]


In [124]:
var1 = np.matrix([[1,2,3],[4,5,6]])
var2 = np.matrix([[1,2,3],[4,5,6]])
print(var1)
print(var2)

print()
print(var1*var2)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]



ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [126]:
var1 = np.array([[1,2,3],[4,5,6]])
var2 = np.array([[1,2,3],[4,5,6]])
print(var1)
print(var2)

print()
print(var1*var2)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]

[[ 1  4  9]
 [16 25 36]]


In [127]:
var1 = np.matrix([[1,2,3],[4,5,6]])
var2 = np.matrix([[1,2,3],[4,5,6]])
print(var1)
print(var2)

print()
print(var1.dot(var2))

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]



ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [128]:
var1 = np.matrix([[1,2],[4,5]])
var2 = np.matrix([[1,2],[4,5]])
print(var1)
print(var2)

print()
print(var1.dot(var2))

[[1 2]
 [4 5]]
[[1 2]
 [4 5]]

[[ 9 12]
 [24 33]]


# Matrix Functions

In [129]:
var = np.matrix([[1,2,3],[1,2,3]])

print(var)
print()


[[1 2 3]
 [1 2 3]]



# Transpose()

In [130]:
var = np.matrix([[1,2,3],[1,2,3]])

print(var)
print()

print(np.transpose(var))

[[1 2 3]
 [1 2 3]]

[[1 1]
 [2 2]
 [3 3]]


In [131]:
var = np.matrix([[1,2,3],[1,2,3]])

print(var)
print()

print(np.transpose(var))
print()
print(var.T)

[[1 2 3]
 [1 2 3]]

[[1 1]
 [2 2]
 [3 3]]

[[1 1]
 [2 2]
 [3 3]]


# Swapaxes()

In [133]:
var = np.matrix([[1,2,3],[1,2,3]])

print(var)
print()

print(np.swapaxes(var,0,1))

[[1 2 3]
 [1 2 3]]

[[1 1]
 [2 2]
 [3 3]]


In [134]:
var1 = np.matrix([[4,1],[2,3]])

print(var1)
print()

print(np.swapaxes(var1,0,1))

[[4 1]
 [2 3]]

[[4 2]
 [1 3]]


# Inverse()

In [136]:
var = np.matrix([[1,2],[3,4]])

print(var)
print()

print(np.linalg.inv(var))

[[1 2]
 [3 4]]

[[-2.   1. ]
 [ 1.5 -0.5]]


# Power()

In [138]:
var = np.matrix([[2,3],[1,2]])

print(var)
print()

print(np.linalg.matrix_power(var,3))        

[[2 3]
 [1 2]]

[[26 45]
 [15 26]]


In [139]:
var = np.matrix([[2,3],[1,2]])

print(var)
print()

print(np.linalg.matrix_power(var,2))

[[2 3]
 [1 2]]

[[ 7 12]
 [ 4  7]]


In [140]:
var = np.matrix([[2,3],[1,2]])

print(var)
print()

print(np.linalg.matrix_power(var,-2))

[[2 3]
 [1 2]]

[[  7. -12.]
 [ -4.   7.]]


In [141]:
var = np.matrix([[2,3],[1,2]])

print(var)
print()

print(np.linalg.matrix_power(var,0))

[[2 3]
 [1 2]]

[[1 0]
 [0 1]]


# Determinate()

In [142]:
var = np.matrix([[2,3],[1,2]])

print(var)
print()

print(np.linalg.det(var))         # |A|

[[2 3]
 [1 2]]

1.0


In [144]:
var = np.matrix([[2,3,6],[1,2,7],[3,8,9]])

print(var)
print()

print(np.linalg.det(var))         # |A|

[[2 3 6]
 [1 2 7]
 [3 8 9]]

-27.999999999999996
